##########################################################################
FROM mcr.microsoft.com/dotnet/core/aspnet:5.0.1 AS base
WORKDIR /app
#EXPOSE [port]
##########################################################################
FROM mcr.microsoft.com/dotnet/core/sdk:5.0.1 AS build
WORKDIR /app
COPY . .
RUN dotnet restore "Conduit.csproj"
COPY . .
WORKDIR /app/.
RUN dotnet build "Conduit.csproj" -c Release -o /app/build
##########################################################################
FROM build AS publish
RUN dotnet publish "Conduit.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Conduit.dll"]
##########################################################################
LABEL maintainer="EvertecInc" \
      name="user@evertecinc.com" \
      description=" " \
      com.evertecinc.version="" \
      com.evertecinc.language="c#" \
      com.evertecinc.framework=".net core 5.0"
##########################################################################


